#============================#
#===== Database sttings =====#
#============================#
jdbc:
    type: mysql
    driver: com.mysql.jdbc.Driver
    url: ${jdbc_url:jdbc:mysql://120.26.241.98:3306/uniq?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true}
    username: ${jdbc_username:root}
    password: ${jdbc_password:root@123}
    pool:
        initialSize: 10
        maxActive: 20
        minIdle: 3
        
#mybatis
mybatis:
    configLocation: ''
    typeAliasesPackage: vc.thinker.**.model

#短信    
sms:
    handler:
         accountSid: ${sms_handler_accountSid:23830729}
         accountToken: ${sms_handler_accountToken:2456e82477e06bcaae4c567df085df9c}
       

redis:
    host: ${ redis_host:localhost}
    port: ${ redis_port:6379}
    password: ${ redis_password:root123}
    timeout: 7000
    database: 1
    message:
        database: 1
        listener-pool-number: 5
    namespace: flash
    oauth2:
        database: 3
        
 
# Random port for embedded MongoDB
#spring.data.mongodb.host=120.24.252.218
spring:
    profiles:
        active: ${ spring_profiles_active:dev}
    data:
        mongodb:
            database: uniq
            host: ${spring_data_mongodb_host:120.26.241.98}
            port: ${spring_data_mongodb_port:10001}
    redis:
        database: 2
        host: ${ spring_redis_host:localhost}
        port: ${spring_redis_port:6379}
        password: ${ spring_redis_password:root123}

tcp:
    run: ${tcp_run:true}
    port: ${tcp_port:7002}
    akka: 
        #receive: ${tcp_akka_receive:futejiaTcpActors}
        receive: ${tcp_akka_receive:shareTcpActors}

app:
    isProduct: ${app_isProduct:false}
    member:
        appkey: ${app_member_appkey:d668c04f9a51e5d4cd50a39f}
        master:
            secret: ${app_member_master_secret:b3b884255d047f1a329bea4a}


# Server
server:
    port: ${server_port:19091}

command:
    push:
        type: ${command_push_type:mqtt}


management:
    port: ${management_port:15310}
    security:
        enabled: ${management_security_enabled:false}

lbs:
    baidu:
        ak: ${lbs_baidu_ak:joiYACL3gPYaWC9r71mNoxlEtyPUMb2g}
        

#iot paas platform
iot:
  paas:
    id: ${iot_paas_id:1}
    url: ${iot_paas_url:http://gopower.tcp.thinker.vc:8888/}